apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ryanj-test-poi-map-app-dev
  annotations:
    argocd/app-name: ryanj-test-poi-map-app-dev
    backstage.io/kubernetes-id: ryanj-test-poi-map-app-dev
    backstage.io/kubernetes-namespace: ryanj-test
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=ryanj-test-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23DevRHEL/ryanj-test-frontend
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://devspaces.apps.summit23-dr.w6gk.p1.openshiftapps.com//#https://github.com/Summit23DevRHEL/ryanj-test-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:ryanj"
  system: workshop-system-ryanj-test
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-ryanj-test
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:ryanj"
